"""
Report generation service for creating professional PDF reports.

Uses Playwright to render HTML reports and export them as PDFs.
Supports multiple report sections: summary, charts, insights, tables.
"""

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.config import settings
from app.core.exceptions import BadRequestError, InternalServerError, NotFoundError
from app.db.database import db_session
from app.services.dataset_service import get_dataset, get_dataset_dataframe
from app.services.chart_service import generate_chart, list_chart_configs
from app.services.insights_service import list_insights

# ============================================================
# REPORT TEMPLATES
# ============================================================

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            color: #1f2937;
            background: #fff;
            padding: 40px;
        }
        .header {
            border-bottom: 3px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 { font-size: 28px; color: #111827; margin-bottom: 8px; }
        .header .meta { color: #6b7280; font-size: 14px; }
        .section { margin-bottom: 30px; page-break-inside: avoid; }
        .section h2 {
            font-size: 20px;
            color: #1f2937;
            border-left: 4px solid #2563eb;
            padding-left: 12px;
            margin-bottom: 16px;
        }
        .section h3 { font-size: 16px; color: #374151; margin: 12px 0 8px; }
        .insight-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 12px;
        }
        .insight-card .severity {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: 600;
            margin-bottom: 8px;
        }
        .severity-high { background: #fee2e2; color: #991b1b; }
        .severity-medium { background: #fef3c7; color: #92400e; }
        .severity-low { background: #d1fae5; color: #065f46; }
        .severity-info { background: #dbeafe; color: #1e40af; }
        .chart-container {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 16px;
            text-align: center;
        }
        .chart-container img { max-width: 100%; height: auto; }
        .chart-title { font-weight: 600; margin-bottom: 12px; color: #374151; }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }
        .data-table th, .data-table td {
            border: 1px solid #e5e7eb;
            padding: 8px 12px;
            text-align: left;
        }
        .data-table th {
            background: #f3f4f6;
            font-weight: 600;
            color: #374151;
        }
        .data-table tr:nth-child(even) { background: #f9fafb; }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 12px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 20px;
        }
        .stat-box {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 16px;
            text-align: center;
        }
        .stat-box .value { font-size: 24px; font-weight: 700; color: #2563eb; }
        .stat-box .label { font-size: 12px; color: #6b7280; margin-top: 4px; }
        @media print {
            body { padding: 20px; }
            .section { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{title}}</h1>
        <div class="meta">
            Generated on {{generated_at}} | Dataset: {{dataset_name}} | {{row_count}} rows × {{column_count}} columns
        </div>
    </div>

    {{sections}}

    <div class="footer">
        <p>Generated by Data Analytics Platform | {{app_version}}</p>
    </div>
</body>
</html>
"""

SECTION_TEMPLATES = {
    "summary": """
    <div class="section">
        <h2>Executive Summary</h2>
        <div class="stats-grid">
            <div class="stat-box"><div class="value">{row_count}</div><div class="label">Rows</div></div>
            <div class="stat-box"><div class="value">{column_count}</div><div class="label">Columns</div></div>
            <div class="stat-box"><div class="value">{numeric_count}</div><div class="label">Numeric</div></div>
            <div class="stat-box"><div class="value">{categorical_count}</div><div class="label">Categorical</div></div>
        </div>
        <p>{description}</p>
    </div>
    """,
    "insight": """
    <div class="section">
        <h2>{title}</h2>
        {insights}
    </div>
    """,
    "chart": """
    <div class="section">
        <h2>{title}</h2>
        <div class="chart-container">
            <div class="chart-title">{chart_title}</div>
            <img src="data:image/svg+xml;base64,{svg_base64}" alt="{chart_title}" />
        </div>
    </div>
    """,
    "table": """
    <div class="section">
        <h2>{title}</h2>
        <table class="data-table">
            <thead><tr>{headers}</tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    """,
    "text": """
    <div class="section">
        <h2>{title}</h2>
        <p>{content}</p>
    </div>
    """,
}


# ============================================================
# HTML REPORT BUILDER
# ============================================================

def _build_insight_html(insight: dict[str, Any]) -> str:
    """Build HTML for a single insight card."""
    severity = insight.get("severity", "info")
    severity_class = f"severity-{severity}"
    return f"""
    <div class="insight-card">
        <span class="severity {severity_class}">{severity.upper()}</span>
        <h3>{insight["title"]}</h3>
        <p>{insight["description"]}</p>
    </div>
    """


def _build_table_html(df, max_rows: int = 20):
    """Build HTML table from DataFrame."""
    preview_df = df.head(max_rows)
    headers = "".join(f"<th>{col}</th>" for col in preview_df.columns)
    rows = ""
    for _, row in preview_df.iterrows():
        row_html = "".join(f"<td>{val}</td>" for val in row.values)
        rows += f"<tr>{row_html}</tr>"
    return headers, rows


def _build_report_html(
    dataset_id: str,
    title: str,
    sections: list[dict[str, Any]],
) -> str:
    """Build complete HTML report content."""
    import pandas as pd
    import base64

    dataset = get_dataset(dataset_id)
    df = get_dataset_dataframe(dataset_id)

    # Build sections HTML
    sections_html = ""
    for section in sections:
        section_type = section.get("type", "text")
        section_title = section.get("title", "Untitled Section")

        if section_type == "summary":
            numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
            cat_cols = df.select_dtypes(include=["object", "category", "string"]).columns.tolist()
            sections_html += SECTION_TEMPLATES["summary"].format(
                row_count=len(df),
                column_count=len(df.columns),
                numeric_count=len(numeric_cols),
                categorical_count=len(cat_cols),
                description=section.get("content", "Dataset analysis report."),
            )

        elif section_type == "insight":
            insights = list_insights(dataset_id)
            if section.get("insightId"):
                insights = [i for i in insights if i["id"] == section["insightId"]]
            insights_html = "".join(_build_insight_html(i) for i in insights[:10])
            sections_html += SECTION_TEMPLATES["insight"].format(
                title=section_title,
                insights=insights_html,
            )

        elif section_type == "chart":
            chart_id = section.get("chartId")
            if chart_id:
                from app.services.chart_service import get_chart_config
                try:
                    chart_config = get_chart_config(chart_id)
                    chart_data = generate_chart(
                        dataset_id=dataset_id,
                        chart_type=chart_config["chartType"],
                        x_axis=chart_config.get("xAxis"),
                        y_axis=chart_config.get("yAxis"),
                        aggregation=chart_config.get("aggregation", "count"),
                        group_by=chart_config.get("groupBy"),
                        filters=chart_config.get("filters"),
                        title=chart_config.get("title"),
                    )
                    # Generate SVG from chart data using recharts-like SVG
                    svg_content = _generate_chart_svg(chart_data)
                    svg_base64 = base64.b64encode(svg_content.encode()).decode()
                    sections_html += SECTION_TEMPLATES["chart"].format(
                        title=section_title,
                        chart_title=chart_config.get("title", "Chart"),
                        svg_base64=svg_base64,
                    )
                except Exception:
                    sections_html += f'<div class="section"><h2>{section_title}</h2><p>Chart could not be rendered.</p></div>'

        elif section_type == "table":
            headers, rows = _build_table_html(df, max_rows=20)
            sections_html += SECTION_TEMPLATES["table"].format(
                title=section_title,
                headers=headers,
                rows=rows,
            )

        elif section_type == "text":
            sections_html += SECTION_TEMPLATES["text"].format(
                title=section_title,
                content=section.get("content", ""),
            )

    # Assemble full report
    html = REPORT_TEMPLATE.replace("{{title}}", title)
    html = html.replace("{{generated_at}}", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
    html = html.replace("{{dataset_name}}", dataset["name"])
    html = html.replace("{{row_count}}", str(dataset["rowCount"]))
    html = html.replace("{{column_count}}", str(dataset["columnCount"]))
    html = html.replace("{{app_version}}", settings.app_version)
    html = html.replace("{{sections}}", sections_html)

    return html


def _generate_chart_svg(chart_data: dict[str, Any]) -> str:
    """Generate a simple SVG representation of chart data for PDF embedding."""
    data = chart_data.get("data", [])
    chart_type = chart_data.get("chartType", "bar")
    title = chart_data.get("config", {}).get("title", "Chart")

    if not data:
        return f'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300"><text x="300" y="150" text-anchor="middle">No data</text></svg>'

    # Simple bar chart SVG
    width = 600
    height = 300
    margin = {"top": 40, "right": 20, "bottom": 60, "left": 60}
    chart_width = width - margin["left"] - margin["right"]
    chart_height = height - margin["top"] - margin["bottom"]

    # Extract values
    if chart_type == "pie":
        values = [d.get("value", 0) for d in data]
        labels = [d.get("name", "") for d in data]
    elif chart_type == "histogram":
        values = [d.get("count", 0) for d in data]
        labels = [d.get("label", "") for d in data]
    else:
        values = [d.get(list(d.keys())[-1], 0) for d in data if isinstance(d, dict)]
        labels = [str(d.get(list(d.keys())[0], "")) for d in data if isinstance(d, dict)]

    if not values:
        return f'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300"><text x="300" y="150" text-anchor="middle">No valid data</text></svg>'

    max_val = max(values) if values else 1
    bar_width = chart_width / len(values) * 0.8
    bar_gap = chart_width / len(values) * 0.2

    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">',
        f'<rect width="{width}" height="{height}" fill="#f9fafb"/>',
        f'<text x="{width/2}" y="25" text-anchor="middle" font-size="16" font-weight="bold" fill="#374151">{title}</text>',
    ]

    # Bars
    for i, (val, label) in enumerate(zip(values, labels)):
        if max_val == 0:
            bar_height = 0
        else:
            bar_height = (val / max_val) * chart_height
        x = margin["left"] + i * (bar_width + bar_gap) + bar_gap / 2
        y = margin["top"] + chart_height - bar_height
        color = f"hsl({222 + (i * 30) % 360}, 60%, 45%)"
        svg_parts.append(f'<rect x="{x}" y="{y}" width="{bar_width}" height="{bar_height}" fill="{color}" rx="3"/>')

        # Label
        label_x = x + bar_width / 2
        label_y = margin["top"] + chart_height + 20
        svg_parts.append(f'<text x="{label_x}" y="{label_y}" text-anchor="middle" font-size="10" fill="#6b7280">{str(label)[:15]}</text>')

    # Y-axis
    svg_parts.append(f'<line x1="{margin["left"]}" y1="{margin["top"]}" x2="{margin["left"]}" y2="{margin["top"] + chart_height}" stroke="#d1d5db" stroke-width="1"/>')
    # X-axis
    svg_parts.append(f'<line x1="{margin["left"]}" y1="{margin["top"] + chart_height}" x2="{width - margin["right"]}" y2="{margin["top"] + chart_height}" stroke="#d1d5db" stroke-width="1"/>')

    # Y-axis labels
    for i in range(5):
        val = max_val * (i / 4)
        y = margin["top"] + chart_height - (i / 4) * chart_height
        svg_parts.append(f'<text x="{margin["left"] - 10}" y="{y + 4}" text-anchor="end" font-size="10" fill="#6b7280">{val:.0f}</text>')

    svg_parts.append("</svg>")
    return "\n".join(svg_parts)


# ============================================================
# PDF GENERATION
# ============================================================

def generate_pdf_report(
    dataset_id: str,
    title: str,
    sections: list[dict[str, Any]],
) -> str:
    """Generate a PDF report and return the file path.

    Args:
        dataset_id: Dataset identifier.
        title: Report title.
        sections: List of report sections.

    Returns:
        Path to the generated PDF file.

    Raises:
        InternalServerError: If PDF generation fails.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise InternalServerError("Playwright not installed. Run: pip install playwright && playwright install")

    # Build HTML report
    html_content = _build_report_html(dataset_id, title, sections)

    # Create output directory
    report_dir = Path("reports") / dataset_id
    report_dir.mkdir(parents=True, exist_ok=True)

    report_id = str(uuid.uuid4())
    html_path = report_dir / f"{report_id}.html"
    pdf_path = report_dir / f"{report_id}.pdf"

    # Write HTML file
    html_path.write_text(html_content, encoding="utf-8")

    # Generate PDF using Playwright
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page()
            page.goto(f"file://{html_path.absolute()}")
            page.pdf(
                path=str(pdf_path),
                format="A4",
                margin={"top": "20px", "right": "20px", "bottom": "20px", "left": "20px"},
                print_background=True,
            )
            browser.close()
    except Exception as exc:
        raise InternalServerError(f"PDF generation failed: {exc}") from exc

    # Store report metadata in database
    created_at = datetime.now(timezone.utc).isoformat()
    with db_session() as conn:
        conn.execute(
            """
            INSERT INTO reports (id, dataset_id, title, file_path, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (report_id, dataset_id, title, str(pdf_path), created_at),
        )

    return str(pdf_path)


# ============================================================
# REPORT CRUD
# ============================================================

def create_report_config(
    dataset_id: str,
    title: str,
    description: str | None = None,
    section_types: list[str] | None = None,
    include_charts: bool = True,
    include_insights: bool = True,
) -> dict[str, Any]:
    """Create a report configuration and generate the PDF.

    Args:
        dataset_id: Dataset identifier.
        title: Report title.
        description: Optional report description.
        section_types: Types of sections to include.
        include_charts: Whether to include saved charts.
        include_insights: Whether to include AI insights.

    Returns:
        Report metadata with download URL.
    """
    dataset = get_dataset(dataset_id)
    sections: list[dict[str, Any]] = []

    # Always include summary
    sections.append({
        "type": "summary",
        "title": "Executive Summary",
        "content": description or f"Analysis report for {dataset['name']}",
    })

    # Include insights if requested
    if include_insights:
        insights = list_insights(dataset_id)
        if insights:
            sections.append({
                "type": "insight",
                "title": "AI-Generated Insights",
            })

    # Include charts if requested
    if include_charts:
        charts = list_chart_configs(dataset_id)
        for chart in charts[:5]:  # Limit to 5 charts
            sections.append({
                "type": "chart",
                "title": f"Chart: {chart['title']}",
                "chartId": chart["id"],
            })

    # Include data preview table
    sections.append({
        "type": "table",
        "title": "Data Preview",
    })

    # Generate PDF
    pdf_path = generate_pdf_report(dataset_id, title, sections)

    return {
        "id": Path(pdf_path).stem,
        "datasetId": dataset_id,
        "title": title,
        "description": description,
        "filePath": pdf_path,
        "sections": sections,
        "status": "completed",
        "createdAt": datetime.now(timezone.utc).isoformat(),
    }


def list_reports(dataset_id: str) -> list[dict[str, Any]]:
    """List all generated reports for a dataset."""
    with db_session() as conn:
        rows = conn.execute(
            """
            SELECT id, dataset_id, title, file_path, created_at
            FROM reports
            WHERE dataset_id = ?
            ORDER BY created_at DESC
            """,
            (dataset_id,),
        ).fetchall()

    return [
        {
            "id": row["id"],
            "datasetId": row["dataset_id"],
            "title": row["title"],
            "filePath": row["file_path"],
            "createdAt": row["created_at"],
        }
        for row in rows
    ]


def get_report(report_id: str) -> dict[str, Any]:
    """Get a single report by ID."""
    with db_session() as conn:
        row = conn.execute(
            "SELECT id, dataset_id, title, file_path, created_at FROM reports WHERE id = ?",
            (report_id,),
        ).fetchone()

    if row is None:
        raise NotFoundError(f"Report '{report_id}' not found.")

    return {
        "id": row["id"],
        "datasetId": row["dataset_id"],
        "title": row["title"],
        "filePath": row["file_path"],
        "createdAt": row["created_at"],
    }


def delete_report(report_id: str) -> dict[str, str]:
    """Delete a report and its associated files."""
    report = get_report(report_id)

    # Delete file
    file_path = Path(report["filePath"])
    if file_path.exists():
        file_path.unlink()
        # Clean up HTML companion file
        html_path = file_path.with_suffix(".html")
        if html_path.exists():
            html_path.unlink()

    # Delete from database
    with db_session() as conn:
        conn.execute("DELETE FROM reports WHERE id = ?", (report_id,))

    return {"message": "Report deleted successfully."}

